apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |-
    server {
      listen       8080;
      listen  [::]:8080;
      server_name  localhost;

      access_log  /data/nginx/access.log  main;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
    } 